nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

# ensure platform specific binaries needed for GitHub Actions are installed so `--immutable-cache` doesn't fail
supportedArchitectures:
  cpu:
    - current
    - x64
  libc:
    - current
    - glibc
  os:
    - current
    - linux

yarnPath: .yarn/releases/yarn-3.3.0.cjs
