nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.3.0.cjs

# ensure platform specific binaries needed for GitHub Actions are installed so `--immutable-cache` doesn't fail
supportedArchitectures:
  os:
    - "current"
    - "linux"
  cpu:
    - "current"
    - "x64"
  libc:
    - "current"
    - "glibc"
