name: Publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    name: yarn publish
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: yarn install --immutable --immutable-cache
      - name: git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: yarn publish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.YARN_NPM_AUTH_TOKEN }}
