name: Publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    name: yarn publish
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: yarn install --immutable --immutable-cache
      - run: yarn publish
